# Generated by Django 5.1.4 on 2025-03-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarthexassets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="hint",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
