# Generated by Django 5.1.4 on 2025-03-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarthexassets", "0002_asset_hint"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="asset_objects",
            field=models.ManyToManyField(
                through="smarthexassets.AssetMembership", to="smarthexassets.object"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="height",
            field=models.PositiveIntegerField(default=144),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asset",
            name="width",
            field=models.PositiveIntegerField(default=144),
            preserve_default=False,
        ),
    ]
