# Generated by Django 4.1.5 on 2023-01-20 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapGeneration',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('da3976d8-3089-40ab-b646-e985763e7130'), editable=False, primary_key=True, serialize=False)),
                ('map', models.CharField(max_length=500000)),
                ('state', models.CharField(choices=[('OP', 'Open'), ('RU', 'Running'), ('RE', 'Ready')], default='OP', max_length=2)),
            ],
        ),
        migrations.AddConstraint(
            model_name='mapgeneration',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['OP', 'RU', 'RE'])), name='valid_state'),
        ),
    ]
