# Generated by Django 4.1.6 on 2023-02-07 21:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smarthexboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('46fdd607-1f12-4010-890f-a63f2106c328'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('turn', models.IntegerField(default=0)),
                ('handicap', models.CharField(choices=[('SE', 'Settler'), ('CH', 'Chieftain'), ('WA', 'Warlord'), ('PR', 'Prince'), ('KI', 'King'), ('EM', 'Emperor'), ('IM', 'Immortal'), ('DE', 'Deity')], default='SE', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MapModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('f32c4da9-e041-49a3-a671-f75d38bf31c6'), editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500000)),
            ],
        ),
        migrations.AlterField(
            model_name='mapgeneration',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('09c7d14d-1c2b-42ab-8fe7-dc281d94e08c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.CharField(choices=[('AL', 'Alexander'), ('TR', 'Trajan'), ('VI', 'Victoria'), ('MO', 'Montezuma'), ('CY', 'Cyrus'), ('NA', 'Napoleon'), ('CL', 'Cleopatra'), ('BA', 'Barbarossa'), ('PE', 'Peter the Great')], default='AL', max_length=2)),
                ('game', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='smarthexboard.gamemodel')),
            ],
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='map',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='smarthexboard.mapmodel'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('leader__in', ['AL', 'TR', 'VI', 'MO', 'CY', 'NA', 'CL', 'BA', 'PE'])), name='valid_leader'),
        ),
        migrations.AddConstraint(
            model_name='gamemodel',
            constraint=models.CheckConstraint(condition=models.Q(('handicap__in', ['SE', 'CH', 'WA', 'PR', 'KI', 'EM', 'IM', 'DE'])), name='valid_handicap'),
        ),
    ]
