# Generated by Django 4.1.6 on 2023-02-22 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smarthexboard', '0004_remove_playertech_valid_tech_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playertech',
            name='valid_tech_identifier',
        ),
        migrations.AddField(
            model_name='player',
            name='human',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('723a04d6-b611-4c86-8f3a-c71bc5c8cb05'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mapgeneration',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3d18b75a-1d36-477b-9ce3-8acb535b1d60'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mapmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0a9ba6b9-122d-413f-b989-0b4bf3337c07'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='playertech',
            constraint=models.CheckConstraint(condition=models.Q(('tech_identifier__in', ('none', 'mining', 'pottery', 'animalHusbandry', 'sailing', 'astrology', 'irrigation', 'writing', 'masonry', 'archery', 'bronzeWorking', 'wheel', 'celestialNavigation', 'horsebackRiding', 'currency', 'construction', 'ironWorking', 'shipBuilding', 'mathematics', 'engineering', 'industrialization', 'refining'))), name='valid_tech_identifier'),
        ),
    ]
