# Generated by Django 4.2.7 on 2023-11-11 09:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smarthexboard', '0007_alter_gamedatamodel_uuid_alter_mapdatamodel_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapgenerationdata',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gamedatamodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7669c5bd-b609-4bc2-801b-6ee3e57060e4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mapdatamodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5ea97daa-dadc-483b-a06e-ff8769890553'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mapgenerationdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d3dbd52f-61dc-4173-ba92-d5b64ea1db6c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
