# Generated by Django 4.2.7 on 2023-11-15 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smarthexboard', '0008_mapgenerationdata_progress_alter_gamedatamodel_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGenerationData',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('231cc10c-c697-4c67-b81d-e4b6e17f44f7'), editable=False, primary_key=True, serialize=False)),
                ('game', models.CharField(max_length=500000)),
                ('state', models.CharField(choices=[('OP', 'Open'), ('RU', 'Running'), ('RE', 'Ready')], default='OP', max_length=2)),
                ('progress', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='MapGenerationData',
        ),
        migrations.RemoveField(
            model_name='playermodel',
            name='game',
        ),
        migrations.RemoveConstraint(
            model_name='gamedatamodel',
            name='valid_handicap',
        ),
        migrations.RemoveField(
            model_name='gamedatamodel',
            name='handicap',
        ),
        migrations.RemoveField(
            model_name='gamedatamodel',
            name='map',
        ),
        migrations.RemoveField(
            model_name='gamedatamodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gamedatamodel',
            name='turn',
        ),
        migrations.AddField(
            model_name='gamedatamodel',
            name='content',
            field=models.CharField(default='', max_length=500000),
        ),
        migrations.AlterField(
            model_name='gamedatamodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c57ac0db-69de-4bd2-8465-66c017fffc9d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='MapDataModel',
        ),
        migrations.DeleteModel(
            name='PlayerModel',
        ),
        migrations.AddConstraint(
            model_name='gamegenerationdata',
            constraint=models.CheckConstraint(check=models.Q(('state__in', ['OP', 'RU', 'RE'])), name='valid_state'),
        ),
    ]
