# Generated by Django 4.2.7 on 2023-11-22 22:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smarthexboard', '0009_gamegenerationdata_delete_mapgenerationdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedatamodel',
            name='content',
            field=models.CharField(default='', max_length=5242880),
        ),
        migrations.AlterField(
            model_name='gamedatamodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2b2ffb48-d372-4a06-80ec-50fd848198ed'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gamegenerationdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('23a43235-ff6f-4ba0-b832-ffcedd2d5d05'), editable=False, primary_key=True, serialize=False),
        ),
    ]
