# Generated by Django 4.2.7 on 2023-11-22 22:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smarthexboard', '0010_alter_gamedatamodel_content_alter_gamedatamodel_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedatamodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6e18be63-5bcd-4132-9290-bef91ec1cd65'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gamegenerationdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e6c5be71-41fe-411f-b1f2-09e56edb9101'), editable=False, primary_key=True, serialize=False),
        ),
    ]
