# Generated by Django 5.1.4 on 2025-03-20 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarthexboard", "0011_alter_gamedatamodel_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamedatamodel",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("53258c6a-70bc-40a6-af41-4f7fa4aaa4fd"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="gamegenerationdata",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("77a3fc56-d600-4bd1-b120-90bd775e0bbe"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
