# Generated by Django 5.1.4 on 2025-03-20 10:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarthexboard", "0012_alter_gamedatamodel_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamedatamodel",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("512dce28-8e4f-471a-bfe1-efba96cf4486"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="gamegenerationdata",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("b85318c7-d34f-4eb2-8215-3cbe9f4d6257"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
