# Generated by Django 5.1.4 on 2025-03-20 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarthexboard", "0013_alter_gamedatamodel_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamedatamodel",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("831856e6-1ed2-4275-b6df-8d1380c83557"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="gamegenerationdata",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("c47d327d-d46f-4a58-9aa8-7badf9bff7f6"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
