# Generated by Django 5.2.4 on 2025-07-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarthexboard", "0014_alter_gamedatamodel_uuid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=500000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="GameDataModel",
        ),
        migrations.RemoveField(
            model_name="gamegenerationdata",
            name="uuid",
        ),
        migrations.AddField(
            model_name="gamegenerationdata",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
